[phases.setup]
nixPkgs = ['nodejs', 'php81', 'php81Packages.composer']

[phases.install]
cmds = [
    'cd backend && composer install --no-dev --optimize-autoloader',
    'cd frontend && npm ci'
]

[phases.build]
cmds = [
    'cd backend && php artisan config:cache',
    'cd backend && php artisan route:cache',
    'cd backend && php artisan view:cache',
    'cd frontend && npm run build'
]

[start]
cmd = 'cd backend && php artisan serve --host=0.0.0.0 --port=$PORT'